const regions={
'Central New York':{lat:42.93,lng:-75.57,base:59,temp:'55–69°F',rain:38,wind:11,weather:'Partly cloudy',habitat:'Oak, hickory, beech, and mixed hardwood edges are the strongest habitat signals.',timing:'First light through mid-morning, with a second window near sunset.',seasonal:'Early fall feeding is boosted by acorn availability and cool overnight temperatures.',mating:'Late-winter mating can increase movement when food remains accessible.'},
'Adirondacks':{lat:43.9,lng:-74.95,base:67,temp:'43–58°F',rain:31,wind:7,weather:'Cool and clear',habitat:'Mast-heavy conifer/hardwood mixes and creek-edge corridors remain productive.',timing:'Use the first two hours after sunrise before wind strengthens.',seasonal:'Cool nights and abundant mast increase foraging pressure.',mating:'Late-winter and early-spring mating can raise movement in interior forests.'},
'Capital Region':{lat:42.75,lng:-73.8,base:63,temp:'50–66°F',rain:28,wind:8,weather:'Mostly sunny',habitat:'Urban-edge woods, oak stands, and mixed forest parcels are most reliable.',timing:'Early morning and late afternoon are most productive.',seasonal:'Mild fall conditions and hardwood mast improve feeding rates.',mating:'Breeding behavior can elevate movement in late winter and early spring.'},
'Catskills':{lat:42.2,lng:-74.4,base:71,temp:'47–61°F',rain:35,wind:6,weather:'Overcast',habitat:'Oak ridges, beech flats, and dense mixed hardwood cover hold squirrels well.',timing:'Focus on the first hour after dawn and late-day feeding routes.',seasonal:'Lower temperatures and robust mast support longer feeding windows.',mating:'Spring mating pulses raise activity where food and cover are available.'},
'Finger Lakes':{lat:42.88,lng:-77,base:56,temp:'54–68°F',rain:42,wind:13,weather:'Breezy',habitat:'Mixed hardwood stands near nut-producing trees produce the best movement.',timing:'Aim for calm mornings before breezes build through the canopy.',seasonal:'Squirrels respond strongly to concentrated food after rainfall.',mating:'Late-winter mating can produce visible mid-day movement.'},
'Hudson Valley':{lat:41.4,lng:-74.1,base:52,temp:'58–72°F',rain:46,wind:10,weather:'Light showers',habitat:'Transition zones between hardwoods, edges, and mast-rich trees are best.',timing:'Target early morning before humidity and wind build.',seasonal:'Warm conditions reduce movement unless food is abundant.',mating:'Mating periods can add brief surges in movement.'},
'Southern Tier':{lat:42.2,lng:-76.8,base:61,temp:'52–66°F',rain:40,wind:9,weather:'Cloudy',habitat:'Mast-rich hardwood pockets near stream bottoms and field edges are best.',timing:'Work the hour before sunrise and as light reaches the canopy.',seasonal:'Cool, consistent conditions help maintain predictable routes.',mating:'Late-winter activity can increase where food access remains stable.'},
'Western New York':{lat:43,lng:-78.8,base:54,temp:'52–65°F',rain:49,wind:15,weather:'Showers possible',habitat:'Oak and hickory stands near farm edges and creek corridors are productive.',timing:'Choose breaks between rain bands and hunt the first two hours.',seasonal:'Damp conditions reduce mid-day movement unless mast is concentrated.',mating:'Spring breeding pulses can increase movement after rain stabilizes.'}};
const dayNames=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];
const $=id=>document.getElementById(id), clamp=(v,min,max)=>Math.min(Math.max(v,min),max);
let current={data:null,weather:null,raw:null};
function weatherText(code){if(code===0)return'Clear';if(code<=3)return'Partly cloudy';if(code<=48)return'Foggy';if(code<=67)return'Rain';if(code<=77)return'Snow';if(code<=82)return'Showers';return'Thunderstorms'}
async function fetchWeather(data){const url=`https://api.open-meteo.com/v1/forecast?latitude=${data.lat}&longitude=${data.lng}&current=temperature_2m,precipitation,wind_speed_10m,weather_code&hourly=temperature_2m,precipitation_probability,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max,wind_speed_10m_max,weather_code&temperature_unit=fahrenheit&wind_speed_unit=mph&timezone=America%2FNew_York&forecast_days=7`;try{const r=await fetch(url);if(!r.ok)throw Error();return await r.json()}catch(e){return null}}
function getWeather(data,raw){if(!raw)return{temperature:61,precipitation:data.rain,wind:data.wind,description:data.weather};const h=new Date().getHours();return{temperature:Math.round(raw.current?.temperature_2m??61),precipitation:Math.round(raw.hourly?.precipitation_probability?.[h]??data.rain),wind:Math.round(raw.current?.wind_speed_10m??data.wind),description:weatherText(raw.current?.weather_code)} }
function scoreFor(data,w,day=0){const month=new Date().getMonth();const mating=(month<=2||month>=4&&month<=5)?12:5;const temp=Math.abs(w.temperature-55)<25?10:0;const rain=w.precipitation>60?-18:w.precipitation>30?-8:6;const wind=w.wind>18?-16:w.wind>10?-7:5;const dayShift=[0,5,-3,6,9,-5,2][day];return clamp(Math.round(data.base+temp+rain+wind+mating+12+8+dayShift),10,98)}
function makeDays(data,w,raw){$('forecast-list').innerHTML='';const now=new Date();for(let i=0;i<7;i++){const d=new Date(now);d.setDate(now.getDate()+i);const rain=raw?.daily?.precipitation_probability_max?.[i]??clamp(data.rain+(i%3===0?8:-4),8,85);const tempMin=raw?.daily?.temperature_2m_min?.[i],tempMax=raw?.daily?.temperature_2m_max?.[i];const wind=raw?.daily?.wind_speed_10m_max?.[i]??clamp(data.wind+(i%2? -1:2),4,30);const score=scoreFor(data,{...w,precipitation:rain,wind},i);const label=score>=75?'Excellent modeled activity':score>=58?'Fair modeled activity':'Limited modeled activity';const temp=tempMin!=null?`${Math.round(tempMin)}–${Math.round(tempMax)}°F`:data.temp;const el=document.createElement('article');el.className='forecast-item';el.innerHTML=`<div class="forecast-top"><span>${i?' '+dayNames[d.getDay()]+', ': 'Today, '}${d.toLocaleDateString('en-US',{month:'short',day:'numeric'})}</span><span class="score">${score}%</span></div><div class="meter"><span class="meter-marker" style="left:${score}%"></span></div><div class="meter-labels"><span>0%</span><span>100%</span></div><p class="activity-note">${label}</p><div class="weather-grid"><div class="weather-cell"><span>WEATHER</span><strong>${i?weatherText(raw?.daily?.weather_code?.[i]):w.description}</strong></div><div class="weather-cell"><span>TEMP</span><strong>${temp}</strong></div><div class="weather-cell"><span>RAIN</span><strong>${Math.round(rain)}%</strong></div><div class="weather-cell"><span>WIND</span><strong>${Math.round(wind)} mph</strong></div></div>`;$('forecast-list').appendChild(el)}}
function updateDetails(data,w,score){const month=new Date().getMonth();const mating=month<=2||month>=4&&month<=5?15:6;const rain=w.precipitation>50?-18:w.precipitation>25?-8:6;const wind=w.wind>18?-15:w.wind>10?-7:5;$('factor-list').innerHTML=[`Temperature comfort: +${Math.abs(w.temperature-55)<25?10:0}`,`Rain effect: ${rain>=0?'+':''}${rain}`,`Wind effect: ${wind>=0?'+':''}${wind}`,`Mating-season pulse: +${mating}`,'Food availability (mast): +12','Daylight / canopy activity: +8',`Overall predictability: ${score}%`].map(x=>`<li>${x}</li>`).join('');$('regulation-list').innerHTML=['Most of NY gray/fox squirrel season: Sep 1–Feb 28','Daily limit: 6 squirrels combined','Valid NYS small-game license required','Long Island dates and WMU rules differ','Verify current DEC guide before hunting'].map(x=>`<li>${x}</li>`).join('');$('habitat-focus').textContent=data.habitat;$('best-timing').textContent=data.timing;$('seasonal-signal').textContent=`${data.seasonal} ${data.mating}`}
function applySlider(){const value=+$('predictability').value;$('predictability-value').textContent=`${value}%`;if(!current.data)return;const base=scoreFor(current.data,current.weather);const score=clamp(Math.round(base+(value-50)*.35),0,100);$('today-score').textContent=`${score}%`;$('recommendation').textContent=score>=75?'Excellent morning conditions':score>=58?'A fair morning for the woods':'Limited conditions today';$('recommendation-detail').textContent=`Personalized forecast sensitivity: ${value}%. Use the 7-day cards for the weather-adjusted baseline.`;updateDetails(current.data,current.weather,score)}
async function updateForecast(){const data=regions[$('region').value];$('update').textContent='UPDATING…';const raw=await fetchWeather(data);const w=getWeather(data,raw);current={data,weather:w,raw};const base=scoreFor(data,w);$('updated').innerHTML=`${$('region').value} <span>•</span> live 7-day forecast`;$('weather-now').textContent=w.description;$('weather-temp').textContent=`${w.temperature}°F`;$('weather-rain').textContent=`${w.precipitation}%`;$('weather-wind').textContent=`${w.wind} mph`;$('wind-now').textContent=`${w.wind} mph`;$('best-window').textContent=base>=65?'6:42 AM':'7:10 AM';$('predictability').value=base;$('predictability-value').textContent=`${base}%`;makeDays(data,w,raw);applySlider();$('update').textContent='UPDATE FORECAST'}
$('update').addEventListener('click',updateForecast);$('region').addEventListener('change',updateForecast);$('predictability').addEventListener('input',applySlider);document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.add('hidden'));t.classList.add('active');$(t.dataset.tab).classList.remove('hidden')}));updateForecast();
